plugins {
    id 'java'
    id 'application'
}

group = 'twitter'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass = 'twitter.main.Main'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
    test {
        java {
            srcDirs = ['test']
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
    testImplementation 'junit:junit:4.13.2'
}

test {
    useJUnit()
}

run {
    workingDir = project.projectDir
}
